### ISSUE TITLE
Enable web analytics

### ISSUE THREAD

**Issue by acka47** [lobid/lobid.github.com#12]
As the traffic doesn't run via emphytos, we currently can't use the current approach. There are different options:

- Set up emphytos as blog.lobid.org proxy for github pages and use our current aproach
- Add a piwik script to the post.

**Comment by dr0i** [comment]
You could use emphytos like in http://weblog.lobid.org, just be sure to set `ProxyPreserveHost Off` in apache settings. This would keep things more simple because we would have just one way to create statistics.

**Comment by acka47** [comment]
I just disabled the custom domain (blog.lobid.org) for a moment in GitHub pages and everything worked as expected with weblog.lobid.org. Thus, the next move is to adjust (remove?) the CNAM entry for blog.lobid.org so that it points to emphytos, right?

**Comment by dr0i** [comment]
@acka47 right :+1:

**Comment by acka47** [comment]
I removed the custom domain from the GitHub pages settings. blog.lobid.org is working as expected with emphytos as reverse proxy. You can now setup the log analytics, @dr0i .

**Comment by dr0i** [comment]
See http://stats.lobid.org/web-access/blog/.

**Comment by acka47** [comment]
Thanks. +1 and closing.
