### ISSUE TITLE
http://blog.lobid.org/2010/07/building-linked-data-based-index-of.html doesn't resolve anymore

### ISSUE THREAD

**Issue by acka47** [lobid/lobid.github.com#17]
For historic reasons, we should make this work again. The post is for example referenced in http://slides.lobid.org/bibcast16/#/5. I think we have to change some settings in blogger first, where I currently don't have admin rights. @literarymachine, would be great if you could give them to me...

After this, we can set a redirect the URL to the blogger page in the web server.

**Comment by acka47** [comment]
Ping @literarymachine. I am currently thinking about the 10th lobid anniversary in the next year. It would be great to have the two old blog post up and running again until them. Please just give me admin rights for the blog and I will take care of everything else.

**Comment by acka47** [comment]
@literarymachine gave me admin rights and the two historical posts are now back online:

- "lobid.org?" from July 20th 2010 at https://lobidorg.blogspot.com/2010/07/lobidorg.html
- "Building a Linked Data based index of library institutions" from the same day at https://lobidorg.blogspot.com/2010/07/building-linked-data-based-index-of.html

We now have to set two redirects from blog.lobid.org to the blogger posts:

- http://blog.lobid.org/2010/07/lobidorg.html -> https://lobidorg.blogspot.com/2010/07/lobidorg.html
- http://blog.lobid.org/2010/07/building-linked-data-based-index-of.html -> https://lobidorg.blogspot.com/2010/07/building-linked-data-based-index-of.html

Assigning @dr0i to do this.

**Comment by dr0i** [comment]
Done as ReverxeProxy, but seen as redirect (although the redirect was originally proposed by @acka47, it would be nicer to the url starting with "blog.lobid.org").
This is most likely due to the fact that the blog isn't https  enabled yet and so it cannot reverseProxy to a https site.
But should be ok so, @acka47 ?

**Comment by acka47** [comment]
+1 I think a redirect is better than a reverse proxy because of the old posts having a totally different look. Closing.
