### ISSUE TITLE
Auto-generate anchor links for headings

### ISSUE THREAD

**Issue by acka47** [lobid/lobid.github.com#29]
See https://stackoverflow.com/questions/42232704/jekyll-mardown-titles-to-links. We should at least have the link, at best also the links in HTML.

**Comment by acka47** [comment]
Ah, nice. That suffices for now for my purposes.

**Comment by fsteeg** [comment]
Using Anchor JS turned out to be straighforward. Pushed to `29-anchor` if you want to test locally, otherwise I'll just push to master to see it in production.

**Comment by acka47** [comment]
Hm, doesn't work for me with branch `29-anchor`. Anyway, just push to production and I will have a look again.

**Comment by fsteeg** [comment]
Deployed: 
http://blog.lobid.org/2018/07/02/lobid-update.html (the icons appear when hovering over headers)

**Comment by acka47** [comment]
Nice, I can see it now. +1 and closing.
