### ISSUE TITLE
Publish shutdown API 1.x post

### ISSUE THREAD

**Issue by acka47** [lobid/lobid.github.com#34]
@fsteeg I couldn't find the post /branch. Let's publish it on Thursday.

**Comment by fsteeg** [comment]
@acka47 It's in master, but in the `_drafts` folder.

**Comment by acka47** [comment]
I did some adjustments, see https://github.com/lobid/lobid.github.com/commit/490c06f7c9e507a587eabaa4ca19d16bf8190299. As soon as the note on http://lobid.org/api is updated we can publish the post.

**Comment by fsteeg** [comment]
Was published by @acka47 today, closing. See http://blog.lobid.org/2018/07/19/lobid-1-shutdown.html
