### ISSUE TITLE
Write Kibana post(s)

### ISSUE THREAD

**Issue by acka47** [lobid/lobid.github.com#41]
We should open up access to the lobid Kibana instance and then write one (or many, for each service one) blog post(s). It should include:

- how to use Kibana
- some visualizations as iframe
- ...

**Comment by dr0i** [comment]
To embed securely kibana we could use [https://www.elastic.co/de/blog/security-for-elasticsearch-is-now-free](free elasticsearch security), but it's only available at elasticsearch version >6.

**Comment by acka47** [comment]
As we don't use it much and as there are still the security issues, I think this does not make much sense anymore. Closing.
