### ISSUE TITLE
HTTPS for blog broken

### ISSUE THREAD

**Issue by fsteeg** [lobid/lobid.github.com#44]
The blog is not reachable via HTTPS.

Reported by @jschnasse: it asks for an exception, but then fails with forbidden 403.

HTTP works fine. However, http://lobid.org links to https://blog.lobid.org/

**Comment by acka47** [comment]
I think it has been like that all along, hasn't it? We could set the GitHub pages configuration to "enforce https" but will need a certificate for the subdomain...

**Comment by fsteeg** [comment]
I don't think it has always been like this. The blog link at lobid.org would have never worked.

**Comment by dr0i** [comment]
This has always been like that. As @acka47 said, we don't have a certificate.
So this is no bug, nothing broken. Closing.

**Comment by dr0i** [comment]
ping @jschnasse

**Comment by dr0i** [comment]
Uh: a not working https link at the start page _is_ a bug indeed - somehow I didn't noticed that. So here is the fix https://github.com/hbz/lobid/commit/57583936e18a41a20143bb7e06484c09c70ba8bb.
