### ISSUE TITLE
Enable https for blog.lobid.org

### ISSUE THREAD

**Issue by acka47** [lobid/lobid.github.com#47]
As https://github.com/lobid/lobid.github.com/issues/44 says, we never had it for the blog. I was just asked by @programmieraffe about this. We should also get  a certificate for the blog subdomain next time. @dr0i , this is not problematic as one certificate for several subdomains is sufficient, isn't it?

**Comment by dr0i** [comment]
TRue, but we have to renew the certificate. Shall do it next time , but this would normally be in a year or so. Ok 4 u 2 wait?

**Comment by acka47** [comment]
> Ok 4 u 2 wait

+1. Leaving the ticket open.

**Comment by acka47** [comment]
> TRue, but we have to renew the certificate. Shall do it next time , but this would normally be in a year or so. 

The year is over now. Have the certificates already been renewed automatically or so?

**Comment by dr0i** [comment]
Looked at the browser info box about certificate for lobid.org, it says : "Expires on: February 9, 2021".

**Comment by dr0i** [comment]
Opened a collecting issue of all hostnames needing a SSL certificate: #69. In short, we will need only _one_ certificate for _all_ hostnames (also subdomains).

**Comment by acka47** [comment]
Resolved together with https://github.com/lobid/lobid.github.com/issues/69. Closing.
