### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by acka47** [lobid/lobid.github.com#53]
Reported by @hagbeck via email:

Am 28.09.19 um 11:44 schrieb H-G B:
> beim Versuch Euren Blog via Feed zu abonnieren tritt ein Fehler auf.
> 
> https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fblog.lobid.org%2Ffeed.xml

**Comment by fsteeg** [comment]
Deployed to production, see:

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fblog.lobid.org

**Comment by acka47** [comment]
+1 Closing

**Comment by hagbeck** [comment]
+1
