### ISSUE TITLE
Decrease line length

### ISSUE THREAD

**Issue by acka47** [lobid/lobid.github.com#7]
On the desktop, lines are currently very long. It says at http://practicaltypography.com/line-length.html:

> Aim for an av­er­age line length of 45–90 char­ac­ters, in­clud­ing spaces. You can check line length us­ing word count.
> ...
> Al­ter­na­tively, use the al­pha­bet test to set line length. You should be able to fit be­tween two and three al­pha­bets on your line, like so:
>
> abcde­fghijklmnopqrstu­vwxyz­abcde­fghijklmnopqrstu­vwxyz­abcde­fgh
= 2.31 alphabets

**Comment by fsteeg** [comment]
Both in Firefox and Chromium I get lines wrapped at 80-85 characters.

Could you have zoomed out in your browser?

**Comment by fsteeg** [comment]
Wait now I get what you mean: if the browser is super wide, it will get wider, yes.

I don't think that's an issue though. If I make the browser that wide, I think it's odd to have so much blank space around the text.

**Comment by fsteeg** [comment]
I would not oppose making it narrower though.

**Comment by acka47** [comment]
I am for limiting line length but am not sure how to best do this. Maybe like this:

```
body 
{
	min-width: 25em;
	max-width: 33em;
}
```

Source: http://maxdesign.com.au/articles/em/
